export const EVENTS = {
    JOIN_QUIZ: 'JOIN_QUIZ',
    LEAVE_QUIZ: 'LEAVE_QUIZ',
    QUIZ_STARTED: 'QUIZ_STARTED',
    QUIZ_ERROR: 'QUIZ_ERROR',
    QUIZ_COMPLETED: 'QUIZ_COMPLETED',

    // Session Status Events
    SESSION_EVENT: 'SESSION_EVENT',
    START_SESSION: 'START_SESSION',
    SESSION_STARTED: 'SESSION_STARTED',
    SESSION_COMPLETED: 'SESSION_COMPLETED',

    // Game Progress Events
    START_QUESTION: 'START_QUESTION',
    END_QUESTION: 'END_QUESTION',
    QUESTION_STARTED: 'QUESTION_STARTED',
    QUESTION_ENDED: 'QUESTION_ENDED',
    QUESTION_TIMEOUT: 'QUESTION_TIMEOUT',
    NEXT_QUESTION: 'NEXT_QUESTION',

    // Update Events
    SCORE_UPDATE: 'SCORE_UPDATE',
    LEADERBOARD_UPDATE: 'LEADERBOARD_UPDATE',
    SUBMIT_ANSWER: 'SUBMIT_ANSWER',

    // Participant Events
    PARTICIPANT_JOINED: 'PARTICIPANT_JOINED',
    PARTICIPANT_LEFT: 'PARTICIPANT_LEFT',
    PARTICIPANT_READY: 'PARTICIPANT_READY',

    RECONNECT_SESSION: 'RECONNECT_SESSION',
    ANSWER_RESULT: 'ANSWER_RESULT',
}

export const QUIZ_STATUS = {
    WAITING: 'waiting',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
}
