export const EVENTS = {
    JOIN_QUIZ: 'JOIN_QUIZ',
    LEAVE_QUIZ: 'LEAVE_QUIZ',
    QUIZ_STARTED: 'QUIZ_STARTED',
    QUIZ_ERROR: 'QUIZ_ERROR',
    QUIZ_COMPLETED: 'QUIZ_COMPLETED',

    SESSION_EVENT: 'SESSION_EVENT',
    START_SESSION: 'START_SESSION',
    SESSION_STARTED: 'SESSION_STARTED',
    SESSION_COMPLETED: 'SESSION_COMPLETED',

    START_QUESTION: 'START_QUESTION',
    END_QUESTION: 'END_QUESTION',
    QUESTION_STARTED: 'QUESTION_STARTED',
    QUESTION_ENDED: 'QUESTION_ENDED',
    QUESTION_TIMEOUT: 'QUESTION_TIMEOUT',
    NEXT_QUESTION: 'NEXT_QUESTION',

    SCORE_UPDATE: 'SCORE_UPDATE',
    LEADERBOARD_UPDATE: 'LEADERBOARD_UPDATE',
    SUBMIT_ANSWER: 'SUBMIT_ANSWER',

    PARTICIPANT_JOINED: 'PARTICIPANT_JOINED',
    PARTICIPANT_LEFT: 'PARTICIPANT_LEFT',
    PARTICIPANT_READY: 'PARTICIPANT_READY',

    RECONNECT_SESSION: 'RECONNECT_SESSION',
    ANSWER_RESULT: 'ANSWER_RESULT',
}

export const QUIZ_STATUS = {
    WAITING: 'waiting',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
}

export const CACHE_KEYS = {
    LEADERBOARD: 'leaderboard:',
    QUIZ_SESSION: 'quiz-session:',
    TOP_PLAYERS: 'top-players:',
    CURRENT_QUESTION: 'current-question:',
}

/**
 * Redis client injection token
 */
export const REDIS_CLIENT = 'REDIS_CLIENT'

export const QUIZ_CONSTANTS = {
    QUESTION_TIME_LIMIT: 30000, // 30 seconds
    BASE_POINTS: 1000,
    MIN_POINTS_RATIO: 0.2, // Minimum 20% of points for last second answers
    BONUS_THRESHOLD: 0.3, // 30% time remaining for bonus points
    BONUS_MULTIPLIER: 1.5, // 50% bonus points for quick answers
} as const
